### ISSUE TITLE
Schemas and Indexes are not shown if there is no primary index

### ISSUE THREAD

**Issue by JesusTheHun** [couchbaselabs/couchbase_jetbrains_plugin#128]
When a collection has no primary index, the `Schema` and `Indexes` nodes don't show up in the tree.

**Comment by deniswsrosa** [comment]
Thanks for reporting this bug. We will take a look at it shortly.

**Comment by deniswsrosa** [comment]
We can't show the  "indexes" node when there is not at least 1 index present. As we fall back to KV to list the documents.
We also don't show the schema for the same reason. SQL++ infer (that we use for the schema), requires at least 1 index to run.

We don't require the user to create a primary index, as long as there is an index that allows us to run a query against that dataset, it should work. I just tested it using a secondary index and it worked fine.

Let me know if there is a scenario that I didn't cover.

**Comment by JesusTheHun** [comment]
@deniswsrosa for schema I get it but I think you should show it anyway, along with a small text saying "schemas will become available once an index is create".
For indexes, you should still show the node because without it we cannot right click to create an index 🤷‍♂️
