### ISSUE TITLE
Buckets are not removed from the tree after deletion.

### ISSUE THREAD

**Issue by JesusTheHun** [couchbaselabs/couchbase_jetbrains_plugin#129]
If you remove the bucket using the plugin, the bucket will not be removed from the tree, even if you refresh the bucket list.
You have to disconnect and reconnect.

Scopes and collections are correctly removed.

**Comment by deniswsrosa** [comment]
Thanks for the heads up. We will include this fix in the next release.

**Comment by deniswsrosa** [comment]
It was an issue with the SDK. We just updated to the latest version and now it is working fine. The fix will be available in the next release.
