### ISSUE TITLE
[Bug] Create bucket dialog doesn't work (fails silently without creating a bucket)

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/couchbase_jetbrains_plugin#133]
I am using Administrator user on my Couchbase docker 7.2.2-6401 image and when trying to create a new bucket from the UI it is silently fails,
no error shown and clicking "OK" just do nothing.
![image](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/9395306/de98e917-7ac1-4293-9d8d-b03b0fc991fe)

Env:
IntelliJ IDEA 2023.2.4 (Community Edition)
Build #IC-232.10203.10, built on October 24, 2023
Runtime version: 17.0.8.1+7-b1000.32 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    com.couchbase.couchbase-intellij-plugin (1.0.4)

Kotlin: 232-1.9.0-IJ10203.10

**Comment by deniswsrosa** [comment]
I made a few changes that would prevent this to happen. Let me know if the error persists. the fix will be available in the next release
