### ISSUE TITLE
[Bug] Data Import Dialog -  Lists hint missing commas

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/couchbase_jetbrains_plugin#134]
In the Data Import dialog there is a hint for what lists are in the case of our cbexport/import tool.
the hint is missing commas between most of the values.
![image](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/9395306/5f530e2d-f7c2-429f-a0b3-4fa720b3f13f)

**Comment by deniswsrosa** [comment]
Fixed, will be available in the next release:
![Screenshot 2023-11-19 at 12 08 35](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/216006/e0a04fcd-0668-4cad-9582-fd1ec10844bc)
![Screenshot 2023-11-19 at 12 08 41](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/216006/23abfbc4-756d-4797-a7d6-e42053557d36)
![Screenshot 2023-11-19 at 12 08 51](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/216006/a6b0fcc5-5601-4ad4-9cd8-ec9af683802f)
