### ISSUE TITLE
[Enhancement] - Reword Document Creation

### ISSUE THREAD

**Issue by aschneidz** [couchbaselabs/couchbase_jetbrains_plugin#16]
Currently says: "Inform Document Id"

Should be: "New Document"
The next to the entry field: "Document ID"

Also worthwhile writing the cluster.bucket.scope.collection path for the new document

Happy to discuss on slack. But this would mirror Capella UI:
![image](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/113996778/7f25b683-9967-4872-95ae-4fea902839f0)

**Comment by aschneidz** [comment]
Also worth splitting create from open document. As you don't want to accidentally create a document if you write the wrong ID (while trying to open exisiting doc)

**Comment by deniswsrosa** [comment]
It is a good point. I will work on that
