### ISSUE TITLE
Index view stats not working 

### ISSUE THREAD

**Issue by lokesh-couchbase** [couchbaselabs/couchbase_jetbrains_plugin#168]
Index view stats functionality seems to have broken

<img width="1120" alt="image" src="https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/113521973/738badcc-ecc7-489c-8323-0c0b94264806">

**Comment by deniswsrosa** [comment]
Could not reproduce this one. If you find the reason, please reopen.
