### ISSUE TITLE
Top bar in extension to create new workbench/create new connection is not visible

### ISSUE THREAD

**Issue by lokesh-couchbase** [couchbaselabs/couchbase_jetbrains_plugin#169]
This appears to be just visible on my system, i tried to replicate on another system and it was working fine. Most probably some cache broke this. 
![image](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/113521973/6ff4ed6a-7f34-46cd-ab39-5f2cddeafee1)

Just mentioning it here for tracking so that if others are also facing the same issue or not

**Comment by deniswsrosa** [comment]
Could not reproduce. If you find what is happening, please reopen the issue
