### ISSUE TITLE
[Enhancement]  Add support for importing CSV's

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/couchbase_jetbrains_plugin#17]
Currently the only was cbimport/export works is by using JSON in a specific format.
it would be useful to add import of a CSV
for example the dataset from time series indexes:
https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/time-series.html#examples

**Comment by deniswsrosa** [comment]
We will add full support for CBExport and CBImport soon.

**Comment by deniswsrosa** [comment]
Work is in progress. Will be done in the next release
