### ISSUE TITLE
Relax document ID constraints

### ISSUE THREAD

**Issue by ldoguin** [couchbaselabs/couchbase_jetbrains_plugin#172]
It seems we have enforces harder rules than needed as to what id a valid document id:
https://github.com/couchbaselabs/couchbase_jetbrains_plugin/blob/276bf21616f5105db830d9abf55922852b5e04a7/src/main/java/com/couchbase/intellij/tree/OpenDocumentDialog.java#L72

My current understanding is that any UTF-8 character is valid in a key.

**Comment by deniswsrosa** [comment]
Yep, you are right. Will fix it asap

**Comment by deniswsrosa** [comment]
Feature is now available in the 1.0.8 version
