### ISSUE TITLE
[Bug] .gitignore creation

### ISSUE THREAD

**Issue by mgroves** [couchbaselabs/couchbase_jetbrains_plugin#18]
This is a very minor nitpick.

- IDE: JetBrains Rider 2023.1.1, running on Windows
- Couchbase Extension 1.0.1

I have a code base with structure like:

```
\
\Conduit
\Conduit\Conduit.Web\
\Conduit\Conduit.Tests\
...etc..
```

My normal .gitignore file is in the root folder. The .NET solution file is in \Conduit.

When I start working with the Couchbase extension (specifically the SQL++ query workbench portion), a .gitignore file is created in the same folder as the solution (i.e. \Conduit)

![image](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/103484/647e7c86-d4ba-4067-88ef-2b98bbb950f6)

I'm not sure what the expected behavior should be. I don't necessarily think it should check one folder up for an existing .gitignore, since other code repos could be structured differently.

One option would just be to *not* add/update a .gitignore file. I understand this might be a slight inconvenience, but if someone has structured their project like me, having to deal with a new .gitignore file every time might be a nuisance.

The other option is to leave it as is. There's no harm in having multiple .gitignore files in a repo.

**Comment by deniswsrosa** [comment]
We keep all files in memory now, so this is not an issue anymore
