### ISSUE TITLE
Small text entry when creating scopes (and others)

### ISSUE THREAD

**Issue by mgroves** [couchbaselabs/couchbase_jetbrains_plugin#187]
I was creating a scope from the UI to try out the Mongo migration. The textbox for entering the name is too small:

![image](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/103484/ce52c8cd-1ae8-44bc-a322-a5d2420039ee)

It should be wider--I'd say at least as long as the label above it. There are other boxes like this too, it's not just scope.

I'm on Windows 11, using Rider.

> JetBrains Rider 2023.3.4
> Build #RD-233.14475.66, built on March 6, 2024
> Licensed to Matthew Groves
> You have a perpetual fallback license for this version.
> Subscription is active until December 28, 2024.
> Runtime version: 17.0.10+1-b1087.17 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Windows 11.0
> .NET Core v7.0.10 x64 (Server GC)
> GC: G1 Young Generation, G1 Old Generation
> Memory: 4054M
> Cores: 16
> Registry:
>   editor.config.csharp.support=true
>   ide.experimental.ui=true
> Non-Bundled Plugins:
>   com.couchbase.couchbase-intellij-plugin (1.0.8)
>   com.intellij.ml.llm (233.14475.74)
>

**Comment by deniswsrosa** [comment]
It might be something specific to Rider, as it works fine on windows+ intellij
![Screenshot 2024-04-02 at 18 52 31](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/216006/df533c4b-0a96-4748-a51d-88d1c78f79ec)

I will continue the investigation

**Comment by deniswsrosa** [comment]
It should be fixed in the latest version, please reopen the bug if it persists.
