### ISSUE TITLE
[Enhancement] dump the list of index create statements using UI

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/couchbase_jetbrains_plugin#23]
Would be VERY useful to be able to extract and fetch all index definitions as a list from a specific collection/cluster/scope
one way of doing it today is by using curl - cluster level

curl -s Administrator:password@{indexNodeHostname}:9102/getIndexStatus | python3 -m json.tool | grep definition | sed 's/^"//g' | sed 's/"$/;/g' | sed 's/\\"/"/g'| sed 's/definition//g' | cut -c 18- | sed 's/..$/;/'

or jq 
curl -s Administrator:password@{indexNodeHostname}:9102/getIndexStatus |jq '.status[].definition' | sed 's/^"//g' | sed 's/"$/;/g' | sed 's/\\"/"/g'
 
or just remove the extra lines by code.

**Comment by deniswsrosa** [comment]
Feature is waiting for release
