### ISSUE TITLE
Cluster Overview Bugs

### ISSUE THREAD

**Issue by lokesh-couchbase** [couchbaselabs/couchbase_jetbrains_plugin#39]
I found few bugs on the cluster overview dialog box. Please let me know why some steps were taken and the same can be incorporated in vscode extension as well. Otherwise please update in the intellij

- Resizing the dialog box results in data not getting correctly rendered, it should have been flexed when width is shortened and should have returned to normal state when again enlarged. (Issue in both new and old UI)
![image](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/113521973/385f6b2d-a77d-490c-9542-914f5148ac58)

- In Nodes > System Stats, there are labels Swap Total and Swap Used, They are currently being shown in bytes, please use fmtByte function to show in wither Mbs or Gbs. 

- In Nodes section, There is a black border surrounding the main section view of dialog box. This is inconsistent with other tabs like buckets and general overview. (Issue in both New and Old UI)
![image](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/113521973/872c0474-2ec1-4311-a5d4-50a5cab8c333)

- There are few datapoints which doesn't have any value. e.g. Spatial Data Size on Disk usually return undefined when Rest API is called. Currently 0 is being shown in these cases. However some other method should be incorporated like either removing the field or showing NA

- In Buckets > Basic Stats, There is field named Item Count. On intellij it has . on wrong point, instead it should have ,
<img width="421" alt="image" src="https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/113521973/eed236ba-ab5e-4ee0-9a8e-1aec07681b9b">

**Comment by deniswsrosa** [comment]
- The UI won't be resizable now
- The Black border is because the dialog has a scrollbar, so it is part of the Jetbrains UI

**Comment by lokesh-couchbase** [comment]
> The Black border is because the dialog has a scrollbar, so it is part of the Jetbrains UI

The issue was that this black border is only visible on nodes screen and not on Overview General and buckets. Either we can have that border on all screens for uniformity if it's part of Jetbrains UI
