### ISSUE TITLE
Intellij UI Enhancements

### ISSUE THREAD

**Issue by lokesh-couchbase** [couchbaselabs/couchbase_jetbrains_plugin#45]
I have found some slight enhancements for plugin, so having them all here. We can discuss what needs to be fixed or will work.

1.  On New UI. On the right click menu, on hover we don't see a pointer. Moreover there is no background change which can give adequate feedback on hover. I think this is an intellij issue but this doesn't looks that good now because of the changes. 
Maybe we can take this up later as people will start switching to new UI.
<img width="344" alt="image" src="https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/113521973/56d83393-4015-4ed5-9604-7bba657549e4">
 
 
 2. Can we show few lines of console in this. (Older lines might still look better than a 1 liner). I don't know what all is possible with PIllowFight CLI, but a status bar or some mathematical data would help others determine the time it will take.
<img width="378" alt="image" src="https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/113521973/85fa6c2a-28c3-45aa-b1b9-21e419688351">

3. Can we do max 100 history elements and remove the first one when writing the 101th one. The way it it now is if someone mistakenly clicks on back, he looses his work. Cmd+Z will save him but this way history feature can be utilized to the fullest.
<img width="888" alt="image" src="https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/113521973/e9d84e1d-800d-4801-9be9-bbe2c11cdf8c">

**Comment by deniswsrosa** [comment]
@lokesh-couchbase Not sure how you are getting this print on pillow fight. It shows exactly what we get from the command line tool
![Screenshot 2023-08-12 at 12 26 44 AM](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/216006/0fb8a501-48cb-47ca-948a-48308e47ac16)


1-Seems to be a problem with the new UI. We are using standard JB components.
3-Pretty minor, we will revisit that when we touch the history again.
