### ISSUE TITLE
Add graphics for cluster structure and services

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/couchbase_jetbrains_plugin#5]
Add ability to see the cluster schematics, 
for example if the cluster have 
3 data nodes of 128GB RAM/16VCPU
2 index node - 128GB RAM/8VCPU
2 query - 32GB RAM/16VCPU
2 FTS - 32GB RAM/16VCPU
2 Analytics  - 32GB RAM/32VCPU

Present the cluster in a graphics way to easy understand which cluster is in the works

**Comment by deniswsrosa** [comment]
+1
