### ISSUE TITLE
[Enhancement] Add Edit Connection screen

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/couchbase_jetbrains_plugin#58]
_Problem:_ Currently there is no option to change the connection after creating it. requiring you to delete it and recreate it.
_Suggestion:_ add the ability to edit the connection before or after connecting to the cluster.
While connected, it might be in read-only mode. if not connected you will be able to change/edit it.

**Comment by deniswsrosa** [comment]
duplicated issue
