### ISSUE TITLE
[Enhancement] Add ability to Tag environments and warn users of sensitive operations

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/couchbase_jetbrains_plugin#7]
Sometime people would use it to access production or other sensitive environments. we must add an option to mark/tag environments, with color, or any other solution.
additionally, tag production as "read only" might be a good idea.

**Comment by deniswsrosa** [comment]
We added the colors. 
@roikatz shouldn't the user have readonly credentials then?

**Comment by roikatz** [comment]
@deniswsrosa  - Not necessarily, it might be easy to change files with that utility, so at least have the option to set a toggle for an environment to be read only, to be on the safe side.

**Comment by deniswsrosa** [comment]
Work is in progress. This feature will be available in the next release
